// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Zkl72oCZDHMrRaj9xCGxQNT2ylMXU4c',
    appId: '1:689885323017:web:95ef24196b7c9ef498fdd8',
    messagingSenderId: '689885323017',
    projectId: 'netflutter',
    authDomain: 'netflutter.firebaseapp.com',
    storageBucket: 'netflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAczo24tUBYQejrWpy8cB3_igO14nbeEyM',
    appId: '1:689885323017:android:26ffa00a0bed193a98fdd8',
    messagingSenderId: '689885323017',
    projectId: 'netflutter',
    storageBucket: 'netflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP9GNRPfH1-QlnJe3lLDgWrPtCcZHkdxk',
    appId: '1:689885323017:ios:2d38d705d2f4e2b398fdd8',
    messagingSenderId: '689885323017',
    projectId: 'netflutter',
    storageBucket: 'netflutter.appspot.com',
    iosClientId: '689885323017-hvg3sjdp0punuepqg70d9cmojjqdhtni.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP9GNRPfH1-QlnJe3lLDgWrPtCcZHkdxk',
    appId: '1:689885323017:ios:2d38d705d2f4e2b398fdd8',
    messagingSenderId: '689885323017',
    projectId: 'netflutter',
    storageBucket: 'netflutter.appspot.com',
    iosClientId: '689885323017-hvg3sjdp0punuepqg70d9cmojjqdhtni.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflutter',
  );
}
